name: CI

on:
  push:

jobs:
  ci:
    name: CI - Analisis y prueba
    runs-on: ubuntu-latest
    steps:
      - name: Descarga local del repositorio
        uses: actions/checkout@v4

      - name: configurar node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas unitarias
        run: npm test

      - name: analizar codigo
        run: npm lint
        
